### ISSUE TITLE
AWS https mode does not support 6MB return value size

### ISSUE THREAD

**Issue by hikoma** [faastjs/faast.js#751]
[This document](https://faastjs.org/docs/aws#queue-vs-https-mode) says that https mode supports up to 6MB as return value size, but the following code does not works.

```
// functions.ts
export function hello() {
    return "a".repeat(256 * 1024 + 1);
}

// examples.ts
import { faastAws } from "faastjs";
import * as funcs from "./functions";

(async () => {
    const m = await faastAws(funcs, {  mode: "https" });
    try {
        const result = await m.functions.hello();
        console.log(result);
    } finally {
        await m.cleanup();
    }
})();
```

Cloudwatch Logs

```
START RequestId: 89110826-663c-4f25-a328-87c3c694bc19 Version: $LATEST
2021-09-16T10:06:09.452Z undefined INFO faast: successful cold start.
2021-09-16T10:06:09.471Z 89110826-663c-4f25-a328-87c3c694bc19 INFO calling: hello
2021-09-16T10:06:09.471Z 89110826-663c-4f25-a328-87c3c694bc19 INFO    args: []
2021-09-16T10:06:09.471Z 89110826-663c-4f25-a328-87c3c694bc19 INFO    callId: 4043b2a6-8208-43e5-ad40-150d7b5a4cc3
2021-09-16T10:06:09.817Z 89110826-663c-4f25-a328-87c3c694bc19 INFO [25]: faast: started child process for module wrapper.
2021-09-16T10:06:09.818Z 89110826-663c-4f25-a328-87c3c694bc19 INFO [25]: calling: hello
2021-09-16T10:06:09.818Z 89110826-663c-4f25-a328-87c3c694bc19 INFO [25]:    args: []
2021-09-16T10:06:09.818Z 89110826-663c-4f25-a328-87c3c694bc19 INFO [25]:    callId: 4043b2a6-8208-43e5-ad40-150d7b5a4cc3
2021-09-16T10:06:09.825Z 89110826-663c-4f25-a328-87c3c694bc19 INFO [25]: Received message promise
2021-09-16T10:06:09.877Z 89110826-663c-4f25-a328-87c3c694bc19 INFO [25]: Done with this.execute()
2021-09-16T10:06:09.956Z faast:warning InvalidParameterValue: One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
END RequestId: 89110826-663c-4f25-a328-87c3c694bc19
REPORT RequestId: 89110826-663c-4f25-a328-87c3c694bc19 Duration: 494.02 ms Billed Duration: 495 ms Memory Size: 1728 MB Max Memory Used: 115 MB Init Duration: 479.17 ms
```

**Comment by acchou** [comment]
Indeed. At some point the implementation changed to always return results through SQS, which has a 256kb limitation. I believe this was changed in order to support asynchronous generators, so multiple results could be returned. This means an https request won't be sufficient to return the results from a lambda function. I'll fix the documentation to reflect this.

**Comment by acchou** [comment]
BTW, if you do need to return something bigger, you can always put it into an S3 bucket and download it separately. Just return the reference to the S3 object as a string, instead of the contents of the object itself. Then on the client side you can download the object using the aws sdk, command line, or console.

**Comment by hikoma** [comment]
Thank you for confirming.  I'm going to download the result data via S3 objects.

**Comment by acchou** [comment]
Documented by b338c7db5a95b0a399155972aae49bb46b8ff93f
